
# ============================================================
# BURGESS SHALE-STYLE TAPHONOMIC MODEL
# EXPERIMENT 2: ANAEROBIC DECAY SENSITIVITY
# ============================================================
#
# Scientific question:
#
# Does the preservation landscape generated by oxygen
# resupply and microbial oxygen consumption persist when
# tissue degradation continues under anoxic conditions?
#
# Experimental factors:
#   1. Oxygen resupply (D_O2)
#   2. Aerobic respiration (k_resp_aero)
#   3. Relative anaerobic decay (anaerobic_decay_ratio)
#
# Experimental design:
#   - Full factorial parameter grid
#   - Paired stochastic replicates
#   - Identical phi field across treatments within replicate
#   - Matched comparisons against anaerobic_decay_ratio = 0
#
# Primary response:
#   Final tissue survival
#
# Secondary responses:
#   Cumulative anoxia
#   Time to anoxia
#   Final anoxia
#   Final biofilm
#   Tissue-specific survival
#
# ============================================================


# ============================================================
# 1. SETUP
# ============================================================

base_dir <- getwd()

out_dir <- file.path(
  base_dir,
  "outputs",
  "experiment_2"
)

dir.create(
  out_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

source("hallucigenia_bodyplan.R")
source("taphonomy_model_core.R")

set.seed(42)


# ============================================================
# 2. CONSTRUCT MODEL ORGANISM
# ============================================================

bp <- make_hallucigenia_offset(
  N = 100,
  target_row = 10
)

stopifnot(
  is.matrix(bp$C),
  is.matrix(bp$k_tissue),
  is.matrix(bp$tissue),
  identical(dim(bp$C), dim(bp$k_tissue)),
  identical(dim(bp$C), dim(bp$tissue)),
  any(bp$C > 0)
)


# ============================================================
# 3. EXPERIMENTAL PARAMETERS
# ============================================================

D_O2_values <- seq(
  0.05,
  0.50,
  length.out = 7
)

resp_values <- seq(
  0.025,
  0.100,
  length.out = 7
)

anaerobic_decay_values <- c(
  0,
  0.10,
  0.25,
  0.50,
  0.75,
  1.00
)

# Use 5 for initial diagnostic runs.
# Increase to 20 for the full experiment.

n_replicates <- 5L

# Spatial heterogeneity bounds

phi_min <- 0.2
phi_max <- 1.0

# Base seed for deterministic stochastic fields

base_seed <- 42000L


# ============================================================
# 4. PARAMETER GRID
# ============================================================

parameter_grid <- expand.grid(

  D_O2 = D_O2_values,

  k_resp_aero = resp_values,

  anaerobic_decay_ratio =
    anaerobic_decay_values,

  replicate = seq_len(n_replicates),

  KEEP.OUT.ATTRS = FALSE,

  stringsAsFactors = FALSE
)

parameter_grid$simulation_id <-
  seq_len(nrow(parameter_grid))

parameter_grid$phi_seed <-
  base_seed + parameter_grid$replicate


cat(
  "\nEXPERIMENT 2: ANAEROBIC DECAY SENSITIVITY\n",
  "========================================\n",
  "Oxygen resupply levels: ",
  length(D_O2_values),
  "\n",
  "Respiration levels: ",
  length(resp_values),
  "\n",
  "Anaerobic decay levels: ",
  length(anaerobic_decay_values),
  "\n",
  "Replicates: ",
  n_replicates,
  "\n",
  "Total simulations: ",
  nrow(parameter_grid),
  "\n\n",
  sep = ""
)


# ============================================================
# 5. GENERATE PAIRED STOCHASTIC FIELDS
# ============================================================
#
# Each replicate has one fixed phi field.
#
# The same field is used across:
#   - all oxygen resupply values
#   - all respiration values
#   - all anaerobic decay ratios
#
# This is a common-random-numbers design.
#
# ============================================================

phi_fields <- vector(
  "list",
  n_replicates
)

for (rep in seq_len(n_replicates)) {

  set.seed(base_seed + rep)

  phi_fields[[rep]] <- matrix(

    runif(
      length(bp$C),
      min = phi_min,
      max = phi_max
    ),

    nrow = nrow(bp$C),
    ncol = ncol(bp$C)
  )
}


# ============================================================
# 6. VALIDATE STOCHASTIC FIELDS
# ============================================================

for (rep in seq_len(n_replicates)) {

  phi <- phi_fields[[rep]]

  stopifnot(
    is.matrix(phi),
    identical(dim(phi), dim(bp$C)),
    all(is.finite(phi)),
    all(phi >= phi_min),
    all(phi <= phi_max)
  )
}


# ============================================================
# 7. RESULTS STORAGE
# ============================================================

results_list <- vector(
  "list",
  nrow(parameter_grid)
)


# ============================================================
# 8. SIMULATION LOOP
# ============================================================

for (i in seq_len(nrow(parameter_grid))) {

  pars <- parameter_grid[i, ]

  rep_id <- as.integer(pars$replicate)

  # Retrieve the paired spatial heterogeneity field

  phi_current <- phi_fields[[rep_id]]


  # ----------------------------------------------------------
  # Progress reporting
  # ----------------------------------------------------------

  if (
    i == 1 ||
    i %% 50 == 0 ||
    i == nrow(parameter_grid)
  ) {

    cat(
      "Running simulation ",
      i,
      " / ",
      nrow(parameter_grid),
      "\n",
      sep = ""
    )
  }


  # ----------------------------------------------------------
  # Run model
  # ----------------------------------------------------------

  sim <- run_taphonomy_model(

    bp = bp,

    steps = 120,

    D_C = 0.01,

    D_O2 = pars$D_O2,

    bc_top = 1,

    k_resp_aero = pars$k_resp_aero,

    k_resp_anaer = 0.005,

    k_sed = 0.002,

    o2_crit = 0.2,

    anoxia_sharpness = 20,

    k_bio = 0.03,

    biofilm_protection = 0.7,

    anaerobic_decay_ratio =
      pars$anaerobic_decay_ratio,

    phi_min = phi_min,

    phi_max = phi_max,

    phi = phi_current,

    record_history = TRUE
  )


  # ----------------------------------------------------------
  # Extract tissue-specific survival
  # ----------------------------------------------------------

  tissue_results <- as.list(
    sim$final_tissue_survival
  )


  # ----------------------------------------------------------
  # Store outputs
  # ----------------------------------------------------------

  results_list[[i]] <- c(

    list(

      simulation_id =
        pars$simulation_id,

      D_O2 =
        pars$D_O2,

      k_resp_aero =
        pars$k_resp_aero,

      anaerobic_decay_ratio =
        pars$anaerobic_decay_ratio,

      replicate =
        rep_id,

      phi_seed =
        pars$phi_seed,

      final_survival =
        sim$final_survival,

      cumulative_anoxia =
        sim$cumulative_anoxia,

      final_anoxia =
        sim$final_anoxia,

      final_o2 =
        sim$final_o2,

      final_biofilm =
        sim$final_biofilm,

      time_to_anoxia =
        sim$time_to_anoxia
    ),

    tissue_results
  )
}


# ============================================================
# 9. COMBINE RAW RESULTS
# ============================================================

results <- do.call(
  rbind.data.frame,
  results_list
)

rownames(results) <- NULL

results[] <- lapply(
  results,
  as.numeric
)


# ============================================================
# 10. VALIDATE COMPLETE FACTORIAL DESIGN
# ============================================================

expected_n <-
  length(D_O2_values) *
  length(resp_values) *
  length(anaerobic_decay_values) *
  n_replicates

stopifnot(
  nrow(results) == expected_n,
  !anyDuplicated(results$simulation_id),
  !anyNA(results$final_survival),
  all(is.finite(results$final_survival)),
  all(results$final_survival >= 0),
  all(results$final_survival <= 1 + 1e-8)
)


# ------------------------------------------------------------
# Verify treatment pairing
# ------------------------------------------------------------

pair_counts <- aggregate(

  anaerobic_decay_ratio ~

    D_O2 +
    k_resp_aero +
    replicate,

  data = results,

  FUN = length
)

stopifnot(
  all(
    pair_counts$anaerobic_decay_ratio ==
      length(anaerobic_decay_values)
  )
)


# ------------------------------------------------------------
# Verify identical phi seed within each matched block
# ------------------------------------------------------------

seed_counts <- aggregate(

  phi_seed ~

    D_O2 +
    k_resp_aero +
    replicate,

  data = results,

  FUN = function(x) {
    length(unique(x))
  }
)

stopifnot(
  all(seed_counts$phi_seed == 1)
)


# ============================================================
# 11. SAVE RAW RESULTS
# ============================================================

write.csv(

  results,

  file.path(
    out_dir,
    "experiment_2_raw_results.csv"
  ),

  row.names = FALSE
)


# ============================================================
# 12. SUMMARISE PARAMETER COMBINATIONS
# ============================================================

group_columns <- c(
  "D_O2",
  "k_resp_aero",
  "anaerobic_decay_ratio"
)

tissue_columns <- grep(
  "^tissue_",
  names(results),
  value = TRUE
)

response_columns <- c(

  "final_survival",
  "cumulative_anoxia",
  "final_anoxia",
  "final_o2",
  "final_biofilm",

  tissue_columns
)


# ------------------------------------------------------------
# Mean responses
# ------------------------------------------------------------

summary_mean <- aggregate(

  results[response_columns],

  by = results[group_columns],

  FUN = mean
)


# ------------------------------------------------------------
# Standard deviation of preservation
# ------------------------------------------------------------

summary_sd <- aggregate(

  results["final_survival"],

  by = results[group_columns],

  FUN = sd
)

names(summary_sd)[
  names(summary_sd) == "final_survival"
] <- "final_survival_sd"


# ------------------------------------------------------------
# Standard error of preservation
# ------------------------------------------------------------

summary_se <- aggregate(

  results["final_survival"],

  by = results[group_columns],

  FUN = function(x) {
    sd(x) / sqrt(length(x))
  }
)

names(summary_se)[
  names(summary_se) == "final_survival"
] <- "final_survival_se"


# ------------------------------------------------------------
# Time to anoxia
# ------------------------------------------------------------

summary_time <- aggregate(

  results["time_to_anoxia"],

  by = results[group_columns],

  FUN = function(x) {

    if (all(is.na(x))) {
      return(NA_real_)
    }

    mean(x, na.rm = TRUE)
  },

  na.action = na.pass
)

names(summary_time)[
  names(summary_time) == "time_to_anoxia"
] <- "mean_time_to_anoxia"


# ------------------------------------------------------------
# Proportion reaching anoxia
# ------------------------------------------------------------

summary_anoxia_frequency <- aggregate(

  results["time_to_anoxia"],

  by = results[group_columns],

  FUN = function(x) {
    mean(!is.na(x))
  },

  na.action = na.pass
)

names(summary_anoxia_frequency)[
  names(summary_anoxia_frequency) == "time_to_anoxia"
] <- "proportion_reaching_anoxia"


# ============================================================
# 13. COMBINE SUMMARY TABLES
# ============================================================

summary_results <- Reduce(

  function(x, y) {

    merge(
      x,
      y,
      by = group_columns,
      all = TRUE
    )
  },

  list(
    summary_mean,
    summary_sd,
    summary_se,
    summary_time,
    summary_anoxia_frequency
  )
)


# ============================================================
# 14. SAVE SUMMARY RESULTS
# ============================================================

write.csv(

  summary_results,

  file.path(
    out_dir,
    "experiment_2_summary.csv"
  ),

  row.names = FALSE
)


# ============================================================
# 15. PAIRED CONTRASTS AGAINST COMPLETE ARREST
# ============================================================
#
# Baseline:
#   anaerobic_decay_ratio = 0
#
# For each environmental parameter combination and replicate:
#
#   delta_survival = survival(r) - survival(r = 0)
#
# Negative values indicate lower tissue survival relative
# to complete anaerobic arrest.
#
# ============================================================

baseline <- subset(

  results,

  anaerobic_decay_ratio == 0,

  select = c(
    "D_O2",
    "k_resp_aero",
    "replicate",
    "final_survival"
  )
)

names(baseline)[4] <-
  "baseline_survival"


paired_results <- merge(

  results,

  baseline,

  by = c(
    "D_O2",
    "k_resp_aero",
    "replicate"
  ),

  all.x = TRUE
)


paired_results$delta_survival <-
  paired_results$final_survival -
  paired_results$baseline_survival


# ============================================================
# 16. VALIDATE PAIRED CONTRASTS
# ============================================================

stopifnot(
  nrow(paired_results) == nrow(results),
  !anyNA(paired_results$baseline_survival),
  !anyNA(paired_results$delta_survival)
)

# The r = 0 treatment must have zero difference from itself.

baseline_differences <- subset(
  paired_results,
  anaerobic_decay_ratio == 0
)

stopifnot(
  all(
    abs(baseline_differences$delta_survival) <
      1e-10
  )
)


# ============================================================
# 17. SAVE INDIVIDUAL PAIRED CONTRASTS
# ============================================================

write.csv(

  paired_results,

  file.path(
    out_dir,
    "experiment_2_paired_contrasts.csv"
  ),

  row.names = FALSE
)


# ============================================================
# 18. SUMMARISE PAIRED SENSITIVITY
# ============================================================

paired_mean <- aggregate(

  delta_survival ~

    D_O2 +
    k_resp_aero +
    anaerobic_decay_ratio,

  data = paired_results,

  FUN = mean
)

names(paired_mean)[4] <-
  "mean_delta_survival"


paired_sd <- aggregate(

  delta_survival ~

    D_O2 +
    k_resp_aero +
    anaerobic_decay_ratio,

  data = paired_results,

  FUN = sd
)

names(paired_sd)[4] <-
  "sd_delta_survival"


paired_se <- aggregate(

  delta_survival ~

    D_O2 +
    k_resp_aero +
    anaerobic_decay_ratio,

  data = paired_results,

  FUN = function(x) {
    sd(x) / sqrt(length(x))
  }
)

names(paired_se)[4] <-
  "se_delta_survival"


paired_summary <- Reduce(

  function(x, y) {

    merge(

      x,
      y,

      by = group_columns,

      all = TRUE
    )
  },

  list(
    paired_mean,
    paired_sd,
    paired_se
  )
)


# ============================================================
# 19. SAVE PAIRED SENSITIVITY SUMMARY
# ============================================================

write.csv(

  paired_summary,

  file.path(
    out_dir,
    "experiment_2_paired_sensitivity_summary.csv"
  ),

  row.names = FALSE
)


# ============================================================
# 20. OVERALL SENSITIVITY
# ============================================================
#
# Mean across the environmental parameter grid.
#
# This describes the chosen simulation parameter space.
# It is not an estimate of real-world preservation frequency.
#
# ============================================================

overall_mean <- aggregate(

  final_survival ~ anaerobic_decay_ratio,

  data = summary_results,

  FUN = mean
)

names(overall_mean)[2] <-
  "mean_survival"


overall_min <- aggregate(

  final_survival ~ anaerobic_decay_ratio,

  data = summary_results,

  FUN = min
)

names(overall_min)[2] <-
  "minimum_survival"


overall_max <- aggregate(

  final_survival ~ anaerobic_decay_ratio,

  data = summary_results,

  FUN = max
)

names(overall_max)[2] <-
  "maximum_survival"


overall_sensitivity <- Reduce(

  function(x, y) {

    merge(
      x,
      y,
      by = "anaerobic_decay_ratio"
    )
  },

  list(
    overall_mean,
    overall_min,
    overall_max
  )
)


# ============================================================
# 21. SAVE OVERALL SENSITIVITY
# ============================================================

write.csv(

  overall_sensitivity,

  file.path(
    out_dir,
    "experiment_2_overall_sensitivity.csv"
  ),

  row.names = FALSE
)


# ============================================================
# 22. DIAGNOSTIC SUMMARY
# ============================================================

cat(
  "\n\nEXPERIMENT 2 RESULTS\n",
  "====================\n\n"
)

cat(
  "Mean survival by anaerobic decay ratio:\n"
)

print(overall_sensitivity)


cat(
  "\nOverall tissue survival range:\n"
)

print(
  range(
    results$final_survival,
    na.rm = TRUE
  )
)


cat(
  "\nMean paired difference relative to r = 0:\n"
)

print(

  aggregate(

    delta_survival ~ anaerobic_decay_ratio,

    data = paired_results,

    FUN = mean
  )
)


# ============================================================
# 23. SAVE EXPERIMENTAL DESIGN
# ============================================================

write.csv(

  parameter_grid,

  file.path(
    out_dir,
    "experiment_2_parameter_grid.csv"
  ),

  row.names = FALSE
)


# ============================================================
# 24. SAVE SESSION INFORMATION
# ============================================================

capture.output(

  sessionInfo(),

  file = file.path(
    out_dir,
    "experiment_2_session_info.txt"
  )
)


# ============================================================
# 25. COMPLETION
# ============================================================

cat(
  "\nExperiment 2 completed successfully.\n",
  "Results saved to:\n",
  out_dir,
  "\n",
  sep = ""
)
